### ISSUE TITLE
[Question] Rake db:create doesn't read the url database.yml param - is it expected?

### ISSUE THREAD

**Issue by hlegius** [TalentBox/sequel-rails#101]
Hello there!
I'm trying to use `rake db:create` but it's returning that I need to provide a database name instead of '' (empty).

I've configured my `config/database/yml` to use only the `url` param instead of all those params separated (database, user, password, etc).

I don't know why but `rake db:migrate` works perfectly within this setup. There is anything special to be done to get it working properly or could it be a bug?

Thanks in advance!

**Comment by mephaust** [comment]
I'm seeing the same problem (using a :sequel namespace) - I think there's something about the rake tasks that follow a different config path:
```
# Fails to create database (config/database.yml is totally removed)
$ RAILS_ENV=production DATABASE_URL='mysql2://root:@localhost/example_service' rake sequel:create[production]
rake aborted!
Adapter not specified in config, please set the :adapter key.


# Fails in a very different way with an invalid adapter
$ RAILS_ENV=production DATABASE_URL='mysqlFoo://root:@localhost/example_service' rake sequel:create[production]
rake aborted!
Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/mysqlfoo
/Users/ph/Documents/src/example-service/config/environment.rb:5:in `<top (required)>'
LoadError: cannot load such file -- sequel/adapters/mysqlfoo
/Users/ph/Documents/src/example-service/config/environment.rb:5:in `<top (required)>'


# Happily finds the adapter when calling migrate!
RAILS_ENV=production DATABASE_URL='mysql2://root@localhost/example_service' rake sequel:migrate[production]
rake aborted!
Sequel::DatabaseConnectionError: Mysql2::Error: Unknown database 'example_service'

Mysql2::Error: Unknown database 'example_service'
```

**Comment by lfittl** [comment]
@hlegius @mephaust I encountered this same issue - could you see if https://github.com/TalentBox/sequel-rails/pull/106 fixes it for you?

**Comment by brennenawana** [comment]
I had a similar issue. My workaround was as follows:
- Open mysql using the same `username` defined in your `database.yml` file. _(Ex. `mysql -u root`)_
-  Create the 'unknown' database manually in mysql. _(Ex. `> CREATE DATABASE example_service;`)_

After I did that my rake tasks ran just fine.

**Comment by cmrd-senya** [comment]
I experience the same `Adapter not specified in config, please set the :adapter key.` with `db:migrate` action when database configuration is provided by URL.
