### ISSUE TITLE
require_valid_table = false on migrations?

### ISSUE THREAD

**Issue by Aryk** [TalentBox/sequel-rails#139]
In order to circumvent this warning:

> SEQUEL DEPRECATION WARNING: Setting a model class dataset to an invalid dataset is deprecated and will be removed in Sequel 5.  Either use a valid dataset or set require_valid_table = false for the model class.

Would it make sense to automatically set 

```ruby
Sequel::Model.require_valid_table = false
```

on migrations only or give a way to do that? What would be the recommended approach? Just to do it manually in each migration?

**Comment by ms-ati** [comment]
Thanks, I came here via google. Can anyone shed any light on how this deprecation was intended by the authors to interact with Rails migrations? I can't find any documentation that would allow a person to avoid this warning, other than what is suggested here?

**Comment by JosephHalter** [comment]
The way I see it, there's just never a good reason to use a model in a migration. Either manipulate the database directly or create a rake task.

**Comment by ms-ati** [comment]
Sorry @JosephHalter, I clarified this is not about migrations, to avoid that discussion. It's about loading the test database schema, which we do in our CI environment.

**Comment by ms-ati** [comment]
This is about the rails environment loading the model class before the database schema has been loaded.

**Comment by JosephHalter** [comment]
I did a quick demo project here: https://github.com/JosephHalter/demo

with nothing but rails and sequel-rails, I added a migration and a model linking to the wrong table, I'm able to run:

```
rake db:drop
rake db:create
rake db:schema:load
```

Without getting any warning.

**Comment by Aryk** [comment]
Got it, will go with @JosephHalter 's suggestion...

**Comment by JosephHalter** [comment]
@Aryk Remember that you can always create datasets without using a model by using `::Sequel::Model.db[:table_name]` so you don't need to revert to SQL while still avoiding to call the model classes in the migrations.

**Comment by nbulaj** [comment]
@JosephHalter it works until some gem would add some models to the project that are required by default, so when you will try to run migrations - it will throw an error (because model is loaded, but table still doesn't exists).

**Comment by art-solopov** [comment]
It looks like `required_valid_table` interferes with migrations created with models.

For instance, if I run `rails g model PaymentMethod` and then try to run the migration, I get `Sequel::DatabaseError`.
