### ISSUE TITLE
Support for Sequel 5.x

### ISSUE THREAD

**Issue by ckoenig** [TalentBox/sequel-rails#142]
Are there any plans to support Sequel 5.x in sequel-rails in the near future?

The only change I can see so far, is a failing test (./spec/lib/sequel_rails/configuration_spec.rb:346). It's suddenly complaining about a missing DB: `PG::ConnectionBad: FATAL:  database "sequel_rails_test_storage_dev" does not exist`. This DB obviously does not exist on my PostgreSQL instance. However, it wasn't complaining about that fact using Sequel 4.x.

If there's anyway I could help, please get back to me. Thanks.

**Comment by bgentry** [comment]
Also interested in this and wondering if I can help! :v:

**Comment by Jesterovskiy** [comment]
https://github.com/TalentBox/sequel-rails/pull/143 @ckoenig @bgentry you can help with fixing test

**Comment by bgentry** [comment]
Sorry I wasn't able to contribute to this earlier, have been slammed the last couple weeks. I took a look at the PR and it does look good afaict

**Comment by eugenk** [comment]
https://github.com/TalentBox/sequel-rails/pull/143 is merged and it's quite an important change. Please make a release :)

**Comment by Jesterovskiy** [comment]
@JonathanTron What do you say about release?)

**Comment by ababich** [comment]
Not sure, what's holding from releasing this to rubygems? 0.9.18 or smth?

**Comment by JonathanTron** [comment]
I've released version 1.0.0 to Rubygems. Thanks everyone for the help!
