### ISSUE TITLE
Pls Open Wiki for Edit/Write

### ISSUE THREAD

**Issue by BKSpurgeon** [TalentBox/sequel-rails#176]
Hello

I thought it might be useful if I wrote a short guide in the wiki, but I could not create it because there are no edit/write privileges in the Wiki.

If you could open that up, that would be great.

Chrs!

Ben

**Comment by JonathanTron** [comment]
Hi @BKSpurgeon thanks for the proposition, if it's fine with you I would prefer to keep the doc in the main repo. You can create a new directory `guides` or `docs` at the root of the repo and create your proposed short guide in it.

**Comment by BKSpurgeon** [comment]
Ok cheers!
