### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by arni1981** [TalentBox/sequel-rails#179]
Hi, I just wanted to know if this repo is actively maintained anymore? I saw that there were some tests added for Rails 6 but no mention of Rails 6 in the README file.

I use Sequel quite a bit and this gem has been really helpful in the past for Rails integration.

**Comment by JonathanTron** [comment]
Hi @arni1981, thank you for asking. Yes the project is still maintain, Rails 6 is supported (and tested against see: https://github.com/TalentBox/sequel-rails/blob/master/.travis.yml#L29).

If you have any ideas of improvements, don't hesitate to open an issue for them or send a Pull Request.

Hint: I think mentioning Rails 6 in the README would be an easy PR ;)
