### ISSUE TITLE
Could not log "sql.sequel" event. when use prepare statements in sequel

### ISSUE THREAD

**Issue by smaginant** [TalentBox/sequel-rails#183]
Hey, I just want to ask a question about prepare statements

https://github.com/jeremyevans/sequel/blob/de22fcd2248b5334ed35f18b799b86771a5b255b/doc/prepared_statements.rdoc#prepared-statements-

when I run this part of code in runtime 
```ruby
ds = Sequel::Model.db[:accounts].where(id: :$id).prepare(:select, :accounts_by_id)
ds.call(id: 1)
```

I receive 
`Could not log "sql.sequel" event. NoMethodError: undefined method 'name' for 1:Integer ["/Users/antonsmagin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sequel-rails-1.1.0/lib/sequel_rails/railties/log_subscriber.rb:44:in `block in sql'"`

I suppose this is because `log_subscriber.rb` expect another bind arguments for logging. Is this is bug? or bind can be passed in different way or in another place? Do you know, may be I can prepare statements in different way?

Thank you

**Comment by JonathanTron** [comment]
Hi @anton-smagin, thanks for reporting the issue. It looks like a bug.

**Comment by Aryk** [comment]
Any updates on this issue? I'm getting a similar issue

**Comment by JonathanTron** [comment]
@smaginant @Aryk Thanks for reporting the problem, I fixed the issue and will release a new version.
