### ISSUE TITLE
Migrations don't work on Rails 7

### ISSUE THREAD

**Issue by opensourceame** [TalentBox/sequel-rails#194]
After doing all the usual config (changing the require all rails gems etc) on Rails 7, it's possible to create the db but migrations do not work. Running `rake db:migrate` gives the undefined constant error.

If you add `config.sequel.load_database_tasks = :sequel` to `config/application.rb` and then run `rake sequel:migrate` the migrations run fine.  So it seems that, for Rails 7, the `rake db:migrate` is not being correctly mapped to Sequel.

I have been using `sequel-rails` for many years on many Rails sites, and it has always worked great until I added it to a bare-bones Rails 7 site.

I briefly perused the code for clues but couldn't see any obvious cause for this.  I suspect some change to railties behaviour in Rails 7 has caused this incompatibility.

**Comment by JonathanTron** [comment]
@opensourceame Thanks for opening the issue, I'll check what I can do.

**Comment by opensourceame** [comment]
Thanks for your reply @JonathanTron, however Rails 7 won't start without ActiveStorage, so it seems we are stuck with using the `sequel:*` task names.

**Comment by opensourceame** [comment]
Actually you can run Rails 7 without ActiveStorage but this requires extra steps. I will make a PR with updated instructions in the readme.

**Comment by opensourceame** [comment]
Closing as this is now explained in the updated [README](https://github.com/TalentBox/sequel-rails#rails-7)
