### ISSUE TITLE
Getting DatabaseDisconnectError in development mode just after start

### ISSUE THREAD

**Issue by managr** [TalentBox/sequel-rails#81]
I'm using latest sequel version together with activerecord in rails 4.1.5.
```
gem 'sequel-rails', '~> 0.9.9'
```
Just added the ```config.sequel.load_database_tasks = false``` to the ```application.rb``` so the rake tasks are not conflicting with activerecord ones.

I'm using sequel for running sql like below:
```
Sequel::Model.db['select * from users'].each { |u| }
```

It's running fine on production but in development I'm always getting
```
Sequel::DatabaseDisconnectError: PG::UnableToSend: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
when I run the query for the 1st time just after rails was loaded. The error is not showing when I run it for the second time. It's also problematic for running specs.
I did try forcing setup using:
```
SequelRails.setup(:development)
```
but it didn't help.

**Comment by JonathanTron** [comment]
Can you provide more details about your stack? 

- Ruby version
- Sequel version
- Ruby server (unicorn, thin, puma, ...)
- Database

**Comment by managr** [comment]
Sure, here they are:
* ruby 2.1.5p273 
* sequel (4.18.0)
* puma (2.9.0)
* postgresql

**Comment by managr** [comment]
Closing the issue. Found the solution.
I've read on the other sequel issue that it's best to disconnect if using forking server:
http://sequel.jeremyevans.net/rdoc/files/doc/code_order_rdoc.html#label-Disconnect+If+Using+Forking+Webserver+with+Code+Preloading

But then found out that the reason was that I was loading extensions in the initializer like that
```
Sequel::Model.db.extension(:pg_array)
Sequel::Model.db.extension(:pg_hstore)
```
By any chance do you know what's the best place for that code (if not rails initializer)?

**Comment by JonathanTron** [comment]
Sorry I just read your answer now. Indeed when using forking server you *have* to disconnect the db connection and reconnect as soon as a worker if forked. Sharing the connection between master and worker do not work.

For Unicorn I'm using something like this in the unicorn config file:

```ruby
before_fork do |server, worker|
  # Ensure we don't keep connections
  if defined?(Sequel)
    ::Sequel::Model.db.disconnect
    ::Sequel::DATABASES.each{|db| db.disconnect }
  end
end

after_fork do |server, worker|
  SequelRails.setup Rails.env if defined?(SequelRails)
end
```

I don't use puma, but it seems like there is an equivalent config file and with similar hooks when ran in forking mode, you can try something like this:

```ruby
on_worker_boot do
  # Ensure we don't keep connections
  if defined?(Sequel)
    ::Sequel::Model.db.disconnect
    ::Sequel::DATABASES.each{|db| db.disconnect }
  end
end

after_worker_boot do
  SequelRails.setup Rails.env if defined?(SequelRails)
end
```

**Comment by JonathanTron** [comment]
As for your db extension, you can use the `after_connect` hook to set them:

```ruby
config.sequel.after_connect = proc do
  Sequel::Model.db.extension(:pg_array)
  Sequel::Model.db.extension(:pg_hstore)
end
```

**Comment by Aryk** [comment]
Hey @JonathanTron, I know this is an old thread. Just curious if it is necessary to put the extensions in the after_connect since the `.extension` method uses after_initialize:

```ruby
    # Register a hook that will be run when a new Database is instantiated. It is
    # called with the new database handle.
    def self.after_initialize(&block)
      raise Error, "must provide block to after_initialize" unless block
      Sequel.synchronize do
        previous = @initialize_hook
        @initialize_hook = Proc.new do |db|
          previous.call(db)
          block.call(db)
        end
      end
    end

    # Apply an extension to all Database objects created in the future.
    def self.extension(*extensions)
      after_initialize{|db| db.extension(*extensions)}
    end
```

Also, this is kind of where I ended up:

```ruby
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i
threads threads_count, threads_count

on_worker_boot do
  # Ensure we don't keep connections
  ::Sequel::Model.db.disconnect
  ::Sequel::DATABASES.each(&:disconnect)
end

after_worker_boot do
  SequelRails.configuration.tap do |config|
    config.max_connections = threads_count
    config.connect Rails.env
  end
end
```

**Comment by JonathanTron** [comment]
Hi @Aryk, the `Sequel::Database.extension` method was added in `Sequel` `3.47.0`, you had to use the `after_connect` hook if you're using a version older than that. 

Nowadays (more than 4 years later), you're probably fine using `Sequel::Database.extension`. ;)

As for your Puma config, it looks fine to me.

**Comment by Aryk** [comment]
cool, thanks for getting back to me on this. I actually ended up with what I think is a "sexier" pure Sequel (no SequelRails) solution. Will roll it into a plugin eventually...

```ruby
Puma::Plugin.create do
  def config(c)
    if workers_supported?
      c.before_fork do
        if defined?(::Sequel)
          Thread.current[:sequel_connect_options] = ::Sequel::DATABASES.map do |db|
            db.disconnect
            db.opts[:orig_opts]
          end
        end
      end
      c.on_worker_boot do
        if defined?(::Sequel)
          Thread.current[:sequel_connect_options].each do |orig_opts|
            ::Sequel.connect(orig_opts)
          end
        end
      end
    end
  end

  VERSION = Puma::Sequel::VERSION
end
```

In case anyone stumbles on this thread. 😄

**Comment by fcwheat** [comment]
@Aryk I stumbled on this thread and your answer^ was exactly what I needed! Note, that if the DB connection is setup using just a URL connection string, then `orig_opts` can be empty but `uri` is populated. We had DBs that connected using both techniques so ended up just returning `db.opts` from the `before_fork` and then doing this in the `on_worker_boot`:
```
if opts[:uri].present?
    ::Sequel.connect(opts[:uri], opts[:orig_opts])
else
    ::Sequel.connect(opts[:orig_opts])
end
```
