### ISSUE TITLE
Any way to disable connect after Rails start?

### ISSUE THREAD

**Issue by BirknerAlex** [TalentBox/sequel-rails#82]
Hello,

is there any way to disable the Sequel.connect process after the Rails/Rake startup? I don't want to use the database.yml File, I need to use a different way to open up multiple database connections.

This works already fine but I need always a dummy connection in the database.yml File because Rails wants to open up a Sequel connection.

If I delete the database.yml File I got this following error:
``` /usr/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/application/configuration.rb:110:in `database_configuration': Cannot load `Rails.application.database_configuration`: (RuntimeError)
Could not load database configuration. No such file - ["config/database.yml"] ```

It should be this line https://github.com/TalentBox/sequel-rails/blob/master/lib/sequel_rails/railtie.rb#L59 but I think there is no way to disable it.

Thank you in advance!

Best regards,
Alexander

**Comment by JonathanTron** [comment]
Indeed, currently there's no way to prevent sequel-rails from connecting to the database.

I'm open to add a configuration allowing to skip the setup step, something like `config.sequel.skip_connect`. Would you be interested to send a pull-request for it?

**Comment by BirknerAlex** [comment]
Done :+1:
