### ISSUE TITLE
structure.sql created if schema_format = :sql is incorrect if postgres schemas are used.

### ISSUE THREAD

**Issue by QuinnHarris** [TalentBox/sequel-rails#86]
The structure.sql dump file created by the postgres database dump tool does not leave the search_path paramater in a predictable state if the database contains different schemas (other than public).  Accordingly the statements to insert the migration rows appended to the structure.sql might not work if the search_path doesn't include the public schema.

This produces the following error
> ERROR:  relation "schema_migrations" does not exist

The following monkey patch fixes this problem for postgres

    module SequelRails
      class Migrations
        class << self
          alias_method :dump_schema_information_orig, :dump_schema_information
    
          def dump_schema_information(opts = {})
            if opts.fetch :sql
              "SET search_path = public, pg_catalog;\n"
            else
              ''
            end + dump_schema_information_orig(opts)
          end
        end
      end
    end

**Comment by JonathanTron** [comment]
Thanks for reporting the issue, please test if it works for you so I can release a new version.
