### ISSUE TITLE
Accessing the DB directly

### ISSUE THREAD

**Issue by toshe** [TalentBox/sequel-rails#87]
Usually when connecting to Sequel you store a virtual database as an object (`Sequel::Database`), e.g.

`DB = Sequel.connect('postgres://localhost/blog?user=user&password=password')`

This way you can query the database by using the DB object, e.g. `DB[:users].all`.

I read the Readme and looked through the code but there doesn't seem to be any info on when the actual connection takes place. 

The thing is, you can always access the database through `Sequel::Model.db` and get this object but you never know if there is a connection. Is there an interface method for that? When can I access the `Sequel::Model.db` earliest?

**Comment by toshe** [comment]
OK, so I created a small initializer under `initializers` with the line

DB = Sequel::Model.db

**Comment by JonathanTron** [comment]
Hi @toshe, 
the connection is made here: https://github.com/TalentBox/sequel-rails/blob/master/lib/sequel_rails/railtie.rb#L63-L67.

So as soon as this initializer has run, you're ready to use `Sequel::Model.db`.

**Comment by JonathanTron** [comment]
So any initializer in your app's `config/initializers` directory can safely access the `Sequel::Model.db` and if you have a `Railtie` with specific initializer you can register them to be loaded after the `sequel.connect` one.
