### ISSUE TITLE
migrations - DB extensions

### ISSUE THREAD

**Issue by mrbrdo** [TalentBox/sequel-rails#95]
Is there something similar to `enable_extension` in ActiveRecord? I wish to create a db extension (e.g. `CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`) in a way so that will be reflected in schema.rb, so that `rake db:reset` will work.

**Comment by JonathanTron** [comment]
No there's no such thing in sequel schema dumper, I'm using `sql dump` when this kind of db specific thing is required, you can enable it by adding the following config in `config/application.rb` file:

```ruby
config.sequel.schema_format = :sql
```
