### ISSUE TITLE
Spring causing Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput()

### ISSUE THREAD

**Issue by mrbrdo** [TalentBox/sequel-rails#97]
If I use spring in development I am getting this error every time, except the first time I run rails console. The first query I run will produce this error, and then it will work fine.
If I run `spring stop` and run rails console it will work with the first query, but then every next time it won't.

It seems part of the problem is that rails initializers only get called the first time due to spring. But I'm not sure why the connection then becomes "bad". Using the connection_validator sequel extension doesn't help.

**Comment by JonathanTron** [comment]
Hi @mrbrdo, it looks like spring requires a special integration. The default handles `ActiveRecord` reconnection (https://github.com/rails/spring/blob/7efd492018049df43310feb89acbaf226446a123/lib/spring/application.rb#L250-L256) but we need something similar for `Sequel`.
I'm not using spring, so a PR to integrate with it would be greatly appreciated.

**Comment by mrbrdo** [comment]
There you go sir :)
