### ISSUE TITLE
`config.sequel.logger` is `nil` in `environment.rb`

### ISSUE THREAD

**Issue by stevenringo** [TalentBox/sequel-rails#98]
Hi,

I am trying to configure `sequel-rails` in various environments to log to a separate logfile from rails's.

Following the pattern of ActiveRecord, where one would put a line like this into an environment config file:
```
config.active_record.logger = nil
```
I am trying:
```
Rails.application.configure do
  config.cache_classes  = false
  ...
  ...
  config.sequel.logger  = SomeSpecialLogger.new(STDOUT)
end
```
In this block `config.sequel.logger` seems to be `nil` anyway (I am somehow expecting it to be assigned), and assigning it here seems to be overwritten later.

Either I am doing something wrong, or `sequel-rails` is not designed to have a logger set at this point in the rails initialization process. I do seem to be apple to apply a different logger in an initializer, like this:
```
SequelRails.configuration.logger = Logger.new(STDOUT)
```
However that would then apply to all environments.

Can anyone advise what is the best way to assign a different logger per environment?

**Comment by JonathanTron** [comment]
Hi @stevenringo, thanks for reporting the problem.

You're right that `sequel.config.logger` value is overwritten (this happens in https://github.com/TalentBox/sequel-rails/blob/master/lib/sequel_rails/railtie.rb#L56-L58).

This is a bug.

**Comment by stevenringo** [comment]
Thanks for the fix! Much appreciated.
